export const JOURNIES = {
  FETCH_JOURNIES: 'FETCH_JOURNIES',
  CLEAR_BOOKJOURNEY_FORM: 'CLEAR_BOOKJOURNEY_FORM',
  UPDATE_FORM_FIELDS: 'UPDATE_FORM_FIELDS',
  SELECTED_A_JOURNEY: 'SELECTED_A_JOURNEY'
};
